-- RUN THIS SQL IN YOUR SUPABASE SQL EDITOR TO CREATE THE BLOG TABLES AND BUCKET

-- Blog stats (views and likes per post ID)
create table if not exists public.blog_stats (
  post_id integer primary key,
  views integer default 0,
  likes integer default 0
);

alter table public.blog_stats enable row level security;
create policy "blog stats are readable by anyone" on public.blog_stats for select using (true);
create policy "blog stats are updatable by anyone" on public.blog_stats for update using (true);

-- Initialize default stats
insert into public.blog_stats (post_id, views, likes)
values (1, 124, 42), (2, 245, 87), (3, 189, 64)
on conflict (post_id) do nothing;

-- Blog comments
create table if not exists public.blog_comments (
  id bigint primary key generated by default as identity,
  post_id integer not null,
  user_id uuid references auth.users(id) on delete set null,
  author_name text not null,
  text text not null,
  attachment_url text,
  attachment_type text,
  likes integer default 0,
  created_at timestamptz default now()
);

alter table public.blog_comments enable row level security;
create policy "blog comments are readable by anyone" on public.blog_comments for select using (true);
create policy "blog comments can be created by anyone" on public.blog_comments for insert with check (true);
create policy "blog comments can be updated by owner" on public.blog_comments for update using (auth.uid() = user_id or user_id is null);
create policy "blog comments can be deleted by owner" on public.blog_comments for delete using (auth.uid() = user_id);

-- Blog comment replies
create table if not exists public.blog_comment_replies (
  id bigint primary key generated by default as identity,
  comment_id bigint not null references public.blog_comments(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  author_name text not null,
  text text not null,
  created_at timestamptz default now()
);

alter table public.blog_comment_replies enable row level security;
create policy "blog comment replies are readable by anyone" on public.blog_comment_replies for select using (true);
create policy "blog comment replies can be created by anyone" on public.blog_comment_replies for insert with check (true);

-- Initialize default comments
insert into public.blog_comments (id, post_id, author_name, text, likes, created_at)
values
  (10001, 1, 'Amara Okoye', 'The Royal Oud sounds absolutely magnificent. Exactly what I need for evening events!', 4, now() - interval '2 hours'),
  (10002, 2, 'Tolu Omoniyi', 'wow thats beautiful u feel me', 1, now() - interval '3 minutes'),
  (10003, 3, 'Chinedu Okafor', 'Super helpful guide. I never realized the differences in EDP and EDT concentrations!', 3, now() - interval '1 day')
on conflict (id) do nothing;

-- Initialize storage bucket for blog attachments
insert into storage.buckets (id, name, public)
values ('blog-attachments', 'blog-attachments', true)
on conflict (id) do nothing;

create policy "blog attachments are public"
  on storage.objects for select
  using (bucket_id = 'blog-attachments');

create policy "anyone can upload blog attachments"
  on storage.objects for insert
  with check (bucket_id = 'blog-attachments');
